//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestForm.MessageCenterSource {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageCenterSource.IMessageCenter")]
    public interface IMessageCenter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageCenter/HelloWorld", ReplyAction="http://tempuri.org/IMessageCenter/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageCenter/HelloWorld", ReplyAction="http://tempuri.org/IMessageCenter/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageCenter/HelloWorldWrite", ReplyAction="http://tempuri.org/IMessageCenter/HelloWorldWriteResponse")]
        void HelloWorldWrite(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageCenter/HelloWorldWrite", ReplyAction="http://tempuri.org/IMessageCenter/HelloWorldWriteResponse")]
        System.Threading.Tasks.Task HelloWorldWriteAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageCenterChannel : TestForm.MessageCenterSource.IMessageCenter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageCenterClient : System.ServiceModel.ClientBase<TestForm.MessageCenterSource.IMessageCenter>, TestForm.MessageCenterSource.IMessageCenter {
        
        public MessageCenterClient() {
        }
        
        public MessageCenterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageCenterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageCenterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageCenterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public void HelloWorldWrite(string message) {
            base.Channel.HelloWorldWrite(message);
        }
        
        public System.Threading.Tasks.Task HelloWorldWriteAsync(string message) {
            return base.Channel.HelloWorldWriteAsync(message);
        }
    }
}
